name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: RaphaCat
          outputs: dist/snake.svg

      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          add: dist/snake.svg
          message: "Generated snake animation"
